name: 'Terraform Post-Merge'

on:
  pull_request:
    types: [closed]

permissions:
  id-token: write
  contents: read

jobs:
  terraform-pre-merge:
    name: 'Terraform Post-Merge'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
         role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsEKSRole
         role-session-name: GitHubActionsSession
         aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (Post-Merge)
        run: terraform plan -input=false

      - name: Terraform Apply (Post-Merge)
        env:
          TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        run: terraform apply -auto-approve -input=false
        if: github.event.pull_request.merged == true