name: 'Terraform Post-Merge'

on:
  pull_request:
    types: [closed]

permissions:
  id-token: write
  contents: read

jobs:
  terraform-pre-merge:
    name: 'Terraform Post-Merge'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (Post-Merge)
        run: terraform plan -input=false

      - name: Terraform Apply (Post-Merge)
        run: terraform apply -auto-approve -input=false
        if: github.event.pull_request.merged == true